notifications:
  email: false
env:
  - RELEASE_BRANCH="master"
language: c
os:
- linux
- osx
sudo: required
services:
  - docker
git:
  submodules: true
compiler:
- gcc
addons:
  apt:
    packages:
    - build-essential
    - gcc
    - make
    - mingw-w64
    - cmake
script:
- mkdir -p build
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . && make && make test; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake . && make && make test; fi
